[package]
name = "ResourceGroupsPrimary"
version = "0.0.0"

[addresses]
resource_groups_primary = "_"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", rev = "mainnet", subdir = "aptos-move/framework/aptos-framework" }
