export default {
  "aptos-white-paper": "Aptosホワイトペーパー",
  "blockchain-deep-dive": "Aptosブロックチェーンの詳細",
  execution: "実行",
  "gas-txn-fee": "ガスとストレージ手数料",
  events: "イベント",
  // TODO: Decide what to do with these pages. Below this line is not included in the information architecture rewrite.
  accounts: "アカウント",
  "validator-nodes": "バリデーターノードの概要",
  fullnodes: "フルノードの概要",
  "node-networks-sync": "ノードネットワークと同期",
  move: "Move - Web3言語とランタイム",
  resources: "リソース",
  "txns-states": "トランザクションと状態",
  "base-gas": "トランザクションガスの計算",
  blocks: "ブロック",
  staking: "ステーキング",
  "delegated-staking": "委任ステーキング",
  governance: "ガバナンス",
};
