[package]
name = "swap"
version = "0.0.0"

[addresses]
aptos_framework = "0x1"
deployer = "_"
swap = "_"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", rev = "mainnet", subdir = "aptos-move/framework/aptos-framework" }
