[package]
name = "DrandLottery"
version = "0.0.1"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", rev = "mainnet", subdir = "aptos-move/framework/aptos-framework" }

[addresses]
std = "0x1"
aptos_std = "0x1"
aptos_framework = "0x1"
drand = "_"
