[tool.poetry]
name = "aptos-sdk"
version = "0.7.1"
description = "Aptos SDK"
authors = ["Aptos Labs <opensource@aptoslabs.com>"]
license = "Apache-2.0"
readme = "README.md"
repository = "https://github.com/aptos-labs/aptos-core"
homepage = "https://github.com/aptos-labs/aptos-core/tree/main/ecosystem/python/sdk"
keywords = ["web3", "sdk", "aptos", "blockchain"]

[tool.poetry.dependencies]
ecdsa = "0.18.0"
h2 = "^4.1.0"
httpx = "^0.24.0"
PyNaCl = "^1.5.0"
python = ">=3.8.1,<4.0"
tomli = "^2.0.1"
typing-extensions = "^4.4.0"

[tool.poetry.dev-dependencies]
autoflake = "2.2.0"
black = "23.7.0"
coverage = "^7.2.4"
flake8 = "6.0.0"
isort = "^5.10.1"
mypy = "^1.0.0"
mypy-extensions = "^1.0.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
