[package]
name = "DataStructure"
version = "0.0.1"

[dependencies]
AptosStdlib = { git = "https://github.com/aptos-labs/aptos-core.git", rev = "mainnet", subdir = "aptos-move/framework/aptos-stdlib" }

[addresses]
std = "0x1"
