name = "code-cache"
main = "src/index.ts"
compatibility_date = "2022-11-07"
# node_compat = true
compatibility_flags = ["nodejs_compat"]

[[ d1_databases ]]
binding = "DB"
database_name = "db"
database_id = "ccfa05ae-ee0e-4727-9222-ea8d74911c74"
migrations_dir = "./drizzle"

[vars]
ENVIRONMENT = "dev"

[env.production.vars]
ENVIRONMENT = "production"