[package]
name = 'my_todo_list'
version = '1.0.0'

AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", rev = "mainnet", subdir = "aptos-move/framework/aptos-framework" }

[addresses]
todolist_addr = '_'