name: Label and tag issue
on:
  issues:
    types: [ opened ]

permissions:
  contents: read

jobs:
  label-component:
    name: Set issue label and tag users/teams as comment
    runs-on: ubuntu-latest
    permissions:
      issues: write
      actions: read
      contents: read
    steps:
      - uses: actions/checkout@v3

      - name: Parse issue form
        uses: stefanbuck/github-issue-parser@v3
        id: issue-parser
        with:
          template-path: .github/ISSUE_TEMPLATE/bug.yml

      - name: Set labels based on the section field
        uses: redhat-plumbers-in-action/advanced-issue-labeler@v2
        with:
          issue-form: ${{ steps.issue-parser.outputs.jsonString }}
          section: section
          block-list: |
            None
            Other
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Add comment tagging relevant teams/users based on the section field
        uses: actions/github-script@v7
        env:
          INPUT_SECTIONS: ${{ steps.issue-parser.outputs.issueparser_section }}
        with:
          script: |
            const script = require('./.github/tagging/script.js')
            await script({
              inputSectionsStr: process.env.INPUT_SECTIONS,
              github,
              context
            })
